export enum TypeOfValues {
    yesNoSelection = 'yesNoSelection',
    inputMultiTags = 'inputMultiTags',
    fullBigString = 'fullBigString',
    colorPicker = 'colorPicker',
    expression = 'expression',
    bigstring = 'bigstring',
    selection = 'selection',
    viewOnly = 'viewOnly',
    boolean = 'boolean',
    string = 'string',
    number = 'number',
    binary = 'binary',
    assign = 'assign',
    hidden = 'hidden',
}
