export enum TypeOfValues {
  stringWithSuggestions = 'stringWithSuggestions',
  multiExpression = 'multiExpression',
  yesNoSelection = 'yesNoSelection',
  inputMultiTags = 'inputMultiTags',
  fullBigString = 'fullBigString',
  multiAssign = 'multiAssign',
  colorPicker = 'colorPicker',
  fieldsTree = 'fieldsTree',
  expression = 'expression',
  optionList = 'optionList',
  stringList = 'stringList',
  bigString = 'bigString',
  selection = 'selection',
  recursive = 'recursive',
  viewOnly = 'viewOnly',
  boolean = 'boolean',
  string = 'string',
  number = 'number',
  binary = 'binary',
  assign = 'assign',
  hidden = 'hidden',
}
